name: Feature request
description: Suggest an idea (a new feature or other improvements) to DOSBox-X
labels: enhancement

body:
  - type: markdown
    attributes:
      value: |
        ### Please fill out the form as cleanly as possible.
        Also, make sure that you have properly filled in the title of the feature request.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct & Contributing Guidelines
      description: By submitting this issue, you agree to follow our [contributing guidelines](https://github.com/joncampbell123/dosbox-x/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/joncampbell123/dosbox-x/blob/master/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow the code of conduct and the contributing guidelines.
          required: true
  - type: checkboxes
    id: alreadyexists
    attributes:
      label: Have you checked that no other similar feature request(s) already exists?
      description: Search the issues before creating this feature request.
      options:
        - label: I have searched and didn't find any similar issues.
          required: true
  - type: textarea
    id: issue
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. If applicable, add screenshots to help in explaining.
      placeholder: "Ex. I'm always frustrated when [...]"
    validations:
      required: false
  - type: textarea
    id: excepted
    attributes:
      label: What you want
      description: A clear and concise description of what you want (to happen). If applicable, add screenshots to help in explaining.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
    validations:
      required: false
